# Generated by Django 5.1.6 on 2025-02-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_vi', models.CharField(blank=True, max_length=200)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('subtitle_vi', models.CharField(blank=True, max_length=300)),
                ('content_en', models.TextField(blank=True)),
                ('content_vi', models.TextField(blank=True)),
                ('font', models.CharField(blank=True, help_text="字体，例如 'Roboto'", max_length=100)),
                ('font_size', models.IntegerField(default=16, help_text='字体大小（px）')),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeContentSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_vi', models.CharField(blank=True, max_length=200)),
                ('content_en', models.TextField(blank=True)),
                ('content_vi', models.TextField(blank=True)),
                ('layout', models.CharField(choices=[('stacked', 'Stacked'), ('carousel', 'Carousel'), ('grid', 'Grid'), ('masonry', 'Masonry')], default='stacked', max_length=50)),
                ('effect', models.CharField(choices=[('hover_zoom', 'Hover Zoom'), ('fade', 'Fade'), ('none', 'None')], default='none', max_length=50)),
                ('text_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('bottom', 'Bottom')], default='right', max_length=10)),
                ('image_spacing', models.IntegerField(default=10, help_text='图片间距，单位像素')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='banners.homecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubtopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_subtopics/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('custom_width', models.IntegerField(blank=True, help_text='自定义宽度（像素）', null=True)),
                ('custom_height', models.IntegerField(blank=True, help_text='自定义高度（像素）', null=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banners.homecontentsubtopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
