# Generated by Django 5.1.6 on 2025-02-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontentsubtopic',
            name='layout',
            field=models.CharField(choices=[('vertical', '垂直布局'), ('horizontal', '水平布局'), ('grid-2', '双列网格')], default='stacked', max_length=50, verbose_name='布局方式'),
        ),
        migrations.AlterField(
            model_name='homecontentsubtopic',
            name='text_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom')], default='right', max_length=10, verbose_name='文字位置'),
        ),
    ]
