# Generated by Django 5.1.6 on 2025-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarousel',
            name='image',
            field=models.ImageField(upload_to='homepage_carousel/'),
        ),
    ]
