# Generated by Django 5.1.6 on 2025-02-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_homecontentsubtopic_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontentsubtopic',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='subtopics', to='banners.subtopicimage'),
        ),
        migrations.AlterField(
            model_name='homecontentsubtopic',
            name='layout',
            field=models.CharField(choices=[('vertical', '垂直布局'), ('horizontal', '水平布局'), ('grid-2', '双列网格')], default='vertical', max_length=50, verbose_name='布局方式'),
        ),
        migrations.AlterField(
            model_name='subtopicimage',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_images', to='banners.homecontentsubtopic'),
        ),
    ]
