# Generated by Django 5.1.6 on 2025-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_homepagecarousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarousel',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/1200x500'),
        ),
    ]
