# Generated by Django 5.1.6 on 2025-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_homepagecarousel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarousel',
            name='image_url',
            field=models.URLField(),
        ),
    ]
