# Generated by Django 5.1.6 on 2025-02-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='控制同一页面中各区块的显示顺序'),
        ),
    ]
