# Generated by Django 5.1.6 on 2025-02-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0004_homepagecarousel_styledsection_styledsectionimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutContent',
        ),
        migrations.DeleteModel(
            name='CareersContent',
        ),
        migrations.DeleteModel(
            name='ContactContent',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='styledsectionimage',
            name='section',
        ),
        migrations.DeleteModel(
            name='SustainabilityContent',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='homepagecarousel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='homepagecarousel',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='homepagecarousel',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='StyledSection',
        ),
        migrations.DeleteModel(
            name='StyledSectionImage',
        ),
    ]
