# Generated by Django 5.1.6 on 2025-02-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0005_delete_aboutcontent_delete_careerscontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='brand_advantage/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='brand_advantage/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='brand_advantage/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
