# Generated by Django 5.1.6 on 2025-02-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0006_brandadvantage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandadvantage',
            old_name='content',
            new_name='main_content',
        ),
        migrations.RenameField(
            model_name='brandadvantage',
            old_name='title',
            new_name='main_title',
        ),
        migrations.RemoveField(
            model_name='brandadvantage',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='brandadvantage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='brandadvantage',
            name='image3',
        ),
        migrations.CreateModel(
            name='BrandAdvantageSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand_advantage_subtopics/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('brand_advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='shundao.brandadvantage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
