# Generated by Django 5.1.6 on 2025-02-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0007_rename_content_brandadvantage_main_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandadvantagesubtopic',
            name='image',
        ),
        migrations.AddField(
            model_name='brandadvantagesubtopic',
            name='effect',
            field=models.CharField(choices=[('hover_zoom', 'Hover Zoom'), ('fade', 'Fade'), ('none', 'None')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='brandadvantagesubtopic',
            name='layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('carousel', 'Carousel'), ('masonry', 'Masonry')], default='grid', max_length=50),
        ),
        migrations.CreateModel(
            name='SubtopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand_advantage_subtopics/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shundao.brandadvantagesubtopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
