# Generated by Django 5.1.6 on 2025-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0008_remove_brandadvantagesubtopic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandadvantagesubtopic',
            name='text_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10),
        ),
    ]
