# Generated by Django 5.1.6 on 2025-02-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0009_brandadvantagesubtopic_text_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandadvantagesubtopic',
            name='text_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('bottom', 'Bottom')], default='right', max_length=10),
        ),
    ]
