# Generated by Django 5.1.6 on 2025-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0010_alter_brandadvantagesubtopic_text_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopicimage',
            name='custom_height',
            field=models.IntegerField(blank=True, help_text='自定义高度（像素），例如200', null=True),
        ),
        migrations.AddField(
            model_name='subtopicimage',
            name='custom_width',
            field=models.IntegerField(blank=True, help_text='自定义宽度（像素），例如300', null=True),
        ),
        migrations.AlterField(
            model_name='brandadvantagesubtopic',
            name='layout',
            field=models.CharField(choices=[('stacked', 'Stacked'), ('carousel', 'Carousel'), ('grid', 'Grid'), ('masonry', 'Masonry')], default='stacked', max_length=50),
        ),
    ]
