# Generated by Django 5.1.6 on 2025-02-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shundao', '0011_subtopicimage_custom_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandadvantagesubtopic',
            name='image_spacing',
            field=models.IntegerField(default=10, help_text='Spacing in pixels between images'),
        ),
    ]
